name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  start_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Frontend
        env:
          AZURE_SSH_FRONTEND_KEY: ${{ secrets.FRONTEND_VM_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_FRONTEND_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.FRONTEND_VM_USER }}@${{ secrets.FRONTEND_VM_HOST }} \
            "cd frontend && \
             git pull origin main && \
             npm install && \
             nohup npm run dev -- --host > frontend.log 2>&1 & echo \$! > frontend.pid && \
             exit 0" &

      - name: Wait for Frontend to be Available
        run: |
          until curl -s http://${{ secrets.FRONTEND_VM_HOST }}:5173 >/dev/null; do
            echo "Waiting for frontend..."
            sleep 5
          done

  start_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Backend
        env:
          AZURE_SSH_BACKEND_KEY: ${{ secrets.BACKEND_VM_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_BACKEND_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.BACKEND_VM_USER }}@${{ secrets.BACKEND_VM_HOST }} \
            "cd backend && \
             sudo mvn clean install -DskipTests && \
             sudo docker-compose up -d --build" &

      - name: Wait for Backend to be Available
        run: |
          until curl -s http://${{ secrets.BACKEND_VM_HOST }}:5000/api/product >/dev/null; do
            echo "Waiting for backend..."
            sleep 5
          done
      
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [start_frontend, start_backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run Cypress Tests on E2E VM
      - name: Run Cypress Tests
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.E2E_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AZURE_VM_USER }}/e2e-tests
            git pull origin main
            npm install
            CYPRESS_baseUrl=http://${{ secrets.FRONTEND_VM_HOST }}:5173 npx cypress run

  stop_frontend:
    runs-on: ubuntu-latest
    needs: e2e-tests  # Run this only after E2E tests
    if: always() 
    steps:
      - name: Stop Frontend
        env:
          AZURE_SSH_FRONTEND_KEY: ${{ secrets.FRONTEND_VM_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_FRONTEND_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.FRONTEND_VM_USER }}@${{ secrets.FRONTEND_VM_HOST }} \
            "pkill -f 'node .*vite' || true" || true

  stop_backend:
    runs-on: ubuntu-latest
    needs: e2e-tests  # Run this only after E2E tests
    if: always() 
    steps:
      - name: Stop Backend
        env:
          AZURE_SSH_BACKEND_KEY: ${{ secrets.BACKEND_VM_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_BACKEND_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.BACKEND_VM_USER }}@${{ secrets.BACKEND_VM_HOST }} \
            "cd backend && \
             sudo docker-compose down" || true
